### ISSUE TITLE
複数行コメント/**/でコメント表示できない

### ISSUE THREAD

**Issue by Riluchi** [tubone24/aiscript-syntax-vscode#2]
非常に興味深い拡張機能でしたので気になった部分をissueさせていただきます。
次の画像の通り、単文コメントのような表示を複数行コメントでもできればより良いと思います。
![image](https://user-images.githubusercontent.com/126536680/230757851-f3a0c6d1-f18c-4322-9a61-ca63cf477bfe.png)

**Comment by tubone24** [comment]
@Riluchi 
ありがとうございます！！ こちら @70165tk にてPRを作っていただきましたのでこちらマージの上、 `0.1.0` のバージョンで公開しております！ご協力ありがとうございました！

**Comment by tubone24** [comment]
@all-contributors please add @Riluchi for ideas
