### ISSUE TITLE
シングルクォートで囲った字を文字列表示できない

### ISSUE THREAD

**Issue by Riluchi** [tubone24/aiscript-syntax-vscode#3]
"ダブルクォート"で囲った文字が文字列表示となっているように、'シングルクォート'、`バッククォート`でも文字列表示してほしい
![image](https://user-images.githubusercontent.com/126536680/230758060-c2c64c7f-a99c-4336-9a99-359cd75239ef.png)

**Comment by tubone24** [comment]
https://github.com/tubone24/aiscript-syntax-vscode/releases/tag/0.2.0
0.2.0でシングルクオート文字列、テンプレート文字列に対応
